x-base-service: &base_service
  build:
    context: .
    dockerfile: ./Dockerfile
  image: ghcr.io/yurifrl/home-systems
  network_mode: host
  environment:
    SSH_AUTH_SOCK: /ssh-agent
    NIXPKGS_ALLOW_BROKEN: 1
    NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
    K3S_TOKEN: $K3S_TOKEN
  volumes:
    - ./cli:/src
    - gomod-cache:/go/pkg/mod
    - $SSH_AUTH_SOCK:/ssh-agent
    - /dev/disk5:/dev/disk5

services:
  sh:
    <<: *base_service
    entrypoint: fish
  nx:
    <<: *base_service
    entrypoint: fish
    working_dir: /src/nixos
  hs:
    <<: *base_service
    entrypoint: go run main.go
    ports:
      - "9110:9110"
  deploy:
    <<: *base_service
    entrypoint: deploy

volumes:
  gomod-cache:
