x-base-service: &base_service
  build:
    context: .
    dockerfile: ./Dockerfile.arm
  image: ghcr.io/yurifrl/home-systems
  working_dir: /src/nix
  volumes:
    - .:/src
    - gomod-cache:/go/pkg/mod
    - $SSH_AUTH_SOCK:/ssh-agent
    - /dev/disk5:/dev/disk5

  environment:
    SSH_AUTH_SOCK: /ssh-agent
  network_mode: host

services:
  sh:
    <<: *base_service
    entrypoint: fish
  hs:
    <<: *base_service
    entrypoint: go run main.go
  deploy:
    <<: *base_service
    entrypoint: deploy
  sh2:
    <<: *base_service
    entrypoint: fish
    privileged: true

volumes:
  gomod-cache:
