apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudders
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    chart: health-check-operator
    repoURL: https://helm.cloudders.com/
    targetRevision: "*"
    helm:
      valuesObject: {}