{{- if .Values.probes.enabled -}}
{{- range .Values.virtualServices }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    probe: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        {{- include "support.hosts" (merge . (dict "Values" $.Values)) | nindent 8 }}
---
{{- end }}
{{- end }}