{{- range .Values.virtualServices }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- include "support.hosts" (merge . (dict "Values" $.Values)) | nindent 4 }}
  gateways:
    - istio-system/private
    - istio-system/public
  http:
    - route:
        - destination:
            host: {{ .service.name }}.{{ .service.namespace }}.svc.cluster.local
            port:
              number: {{ .service.port }}
{{- end }}