apiVersion: v1
kind: Service
metadata:
  name: appdaemon
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5050
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: appdaemon 