name: Release Image

on: [push]

permissions:
  packages: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHA_PAT }}
      - name: Docker pull
        run: |
          docker pull ghcr.io/yurifrl/home-systems
      - name: Build NixOS SD Image
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/yurifrl/home-systems
          options: -v "${{ github.workspace }}:/app"
          run: |
            nix build ./nix#packages.aarch64-linux.default ./nix#packages.x86_64-linux.default --impure
      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-sd-image
          path: ./*.img*
